### ISSUE TITLE
Fishing Website

### ISSUE THREAD

**Issue by atitan** [remcoros/InspectR#23]
Hi,

Recently, I've found several fishing websites listed here (http://www.dinkypage.com/168081) use your service to collect users' personal information.

Their callback url is: http://inspectb.in/31dc0556

Hope you'll kindly remove them.

Regards.

**Comment by remcoros** [comment]
I can't find anything 'fishy' anymore on that page.

Also, I don't see how personal information could be extracted using InspectBin.

Let me know if i'm incorrect.
